Repository approvers/RADWIMPS, pull requests merged in 2020-07, with the labels that each got.

#30 [Ruby] Fix indent
  RADWIMPS.rb
Labels: bug

#49 [Languages] Elixir
  RADWIMPS.exs
Labels: languages/new

#48 [Languages] ReasonML
  RADWIMPS.re
Labels: languages/new

#50 [Languages] FORTH
  RADWIMPS.fth
Labels: languages/new

#52 [Languages] Produire / プロデル
  RADWIMPS.rdr
Labels: languages/new, status/ready

#53 [Languages] Perl
  RADWIMPS.pl
Labels: languages/new

#55 [Languages] PowerShell
  RADWIMPS.ps1
Labels: languages/new

#54 C: メソッドチェーン（大嘘）
  RADWIMPS.c
Labels: languages/fix

#47 [Documentation] 英語版READMEを追加
  README.en.md
  README.md
Labels: documentation

#61 Create LICENSE
  LICENSE
Labels: documentation

#68 Add NScripter
  RADWIMPS.nscripter
Labels: languages/new

#60 Add Clojure
  RADWIMPS.clj
Labels: languages/new

#62 add Julia
  RADWIMPS.jl
Labels: languages/new

#63 [Languages] Hack
  RADWIMPS.hack
Labels: languages/new

#64 [Languages] Raku
  RADWIMPS.raku
Labels: languages/new

#65 [Languages] Racket
  RADWIMPS.rkt
Labels: languages/new

#95 [Languages] Add AppleScript
  RADWIMPS.applescript
Labels: languages/new

#94 [Languages] Add Haxe
  RADWIMPS.hx
Labels: languages/new

#105 [Language] Crystal
  RADWIMPS.cr
Labels: languages/new

#69 Add Delphi Project File
  RADWIMPS.dpr
Labels: languages/new

#70 [Languages] wenyan-lang
  RADWIMPS.wy
Labels: languages/new

#96 [Languages] Zen
  RADWIMPS.zen
Labels: languages/new

#67 [Languages] BuckleScript
  RADWIMPS.res
Labels: languages/new

#107 remove all-contributors-bot
  .all-contributorsrc
  README.md
Labels: status/ready

#108 [Languages] Ada
  RADWIMPS.adb
Labels: languages/new

#98 Improve [bd]ash
  RADWIMPS.bash
  RADWIMPS.dash
Labels: languages/improve

#101 [Languages] Io
  RADWIMPS.io
Labels: languages/new

#112 [Languages] CoffeeScript
  RADWIMPS.coffee
Labels: languages/new

#97 [Languages] Add Visual Basic
  RADWIMPS.vb
Labels: languages/new

#113 [Fix]Scratch
  RADWIMPS.sb3
Labels: languages/improve

#109 [Language] Pascal (objfpc)
  RADWIMPS.p
Labels: languages/new

#110 Improve Python
  RADWIMPS.py
Labels: languages/improve

#114 [Languages] Processing
  RADWIMPS.pde
Labels: languages/new

#116 [Languages] Erlang
  RADWIMPS.erl
Labels: languages/new

#115 [Languages] Arduino
  RADWIMPS.ino
Labels: languages/new

#111 [Languages] Vue
  RADWIMPS.vue
Labels: languages/new

#125 Fix typo
  README.md
Labels: documentation

#132 [Languages] WebAssembly (WASI)
  RADWIMPS.wat
Labels: languages/new

#129 Improve Rust code
  RADWIMPS.rs
Labels: languages/improve
